ScoreManage-main/ScoreManagement/Pages/AccountLogin/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using ScoreManagement.Models;
using System.Security.Claims;
using System.Linq;
using ScoreManagement.Services;

namespace ScoreManagement.Pages.AccountLogin
{
    public class LoginModel : PageModel
    {
        private readonly Project_PRN222Context _context;

        public LoginModel(Project_PRN222Context context)
        {
            _context = context;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public string Username { get; set; }
            public string Password { get; set; }

            public bool RememberMe { get; set; }
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                var account = _context.Accounts.SingleOrDefault(a => a.Username == Input.Username);
                if (account != null && VerifyPassword(Input.Password, account.PasswordHash))
                {
                    var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, Input.Username),
                new Claim(ClaimTypes.Role, account.Role),
                new Claim("AccountId", account.AccountId.ToString())
            };

                    if (account.Role == "LECTURER")
                    {
                        var lecturer = _context.Lecturers.SingleOrDefault(s => s.AccountId == account.AccountId);
                        if (lecturer != null)
                        {
                            // Add LecturerId claim only if lecturer is found
                            claims.Add(new Claim("LecturerId", lecturer.LecturerId.ToString()));
                        }
                    }

                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    // Redirect based on role
                    if (account.Role == "LECTURER")
                    {
                        return RedirectToPage("/LectureMenu/LecturerDashboard");
                    }
                    else if (account.Role == "STUDENT")
                    {
                        var student = _context.Students.SingleOrDefault(s => s.AccountId == account.AccountId);
                        if (student != null)
                        {
                            return RedirectToPage("/StudentMenu/StudentDashboard", new { studentId = student.StudentId });
                        }
                    }
                    else if (account.Role == "ADMIN")
                    {
                        return RedirectToPage("/AdminMenu/AdminDashboard");
                    }
                }
                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
            }
            return Page();
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            Console.WriteLine("Logout function called");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/AccountLogin/Login");
        }



        private bool VerifyPassword(string enteredPassword, string storedPasswordHash)
        {
            //return enteredPassword == storedPasswordHash;
            // Kiểm tra nếu mật khẩu chưa được mã hóa
            if (enteredPassword == storedPasswordHash)
            {
                return true; // Mật khẩu chưa mã hóa trùng khớp
            }

            try
            {
                // Giải mã mật khẩu đã mã hóa
                string decryptedPassword = RSAEncryption.Decrypt(storedPasswordHash);
                Console.WriteLine($"[DEBUG] Password sau khi mã hóa: {decryptedPassword}");

                // So sánh với mật khẩu nhập vào
                return enteredPassword == decryptedPassword;
            }
            catch
            {
                return false; // Nếu giải mã thất bại, mật khẩu không hợp lệ
            }
        }

        
    }
}

ScoreManage-main/ScoreManagement/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ScoreManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ScoreManagement.styles.css" asp-append-version="true" />
    <link href="~/Asset/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="~/Asset/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <div id="wrapper">
            <!-- Include Sidebar -->
            @await Html.PartialAsync("_Sidebar")

            <!-- Content Wrapper -->
            <div id="content-wrapper" class="d-flex flex-column">
                <!-- Main Content -->
                <div id="content">
                    <!-- Include Topbar -->
                    @await Html.PartialAsync("_Topbar")

                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </div>
                <!-- End of Main Content -->
            </div>
            <!-- End of Content Wrapper -->
        </div>
    </header>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Asset/vendor/jquery/jquery.min.js"></script>
    <script src="~/Asset/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Asset/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/Asset/js/sb-admin-2.min.js"></script>
    <script src="/lib/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ScoreManage-main/ScoreManagement/Pages/Shared/_Sidebar.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/AdminMenu/AdminDashboard">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-chart-bar"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Score Management</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/AdminMenu/AdminDashboard">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Admin Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - User Management -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
           aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>User Management</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category:</h6>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/AccountManage/Index">
                    <i class="fas fa-users"></i> Account
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/StudentsManage/Index">
                    <i class="fas fa-user-graduate"></i> Student
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/LecturersManage/Index">
                    <i class="fas fa-chalkboard-teacher"></i> Lecturer
                </a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Academic Management -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-book"></i>
            <span>Learning Management</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category:</h6>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/ClassCoursesManage/Index">
                    <i class="fas fa-book-reader"></i> ClassCourse Management
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/CoursesManage/Index">
                    <i class="fas fa-book"></i> Course Management
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/ClassesManage/Index">
                    <i class="fas fa-school"></i> Class Management
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/MajorManage/Index">
                    <i class="fas fa-graduation-cap"></i> Major Management
                </a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Grade Management -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
           aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-graduation-cap"></i>
            <span>Score Management</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category:</h6>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/GradeManage/Index">
                    <i class="fas fa-chart-line"></i> Score
                </a>
                <a class="collapse-item text-wrap" asp-area="" asp-page="/AdminMenu/StudentsCoursesManage/Index" style="white-space: normal;">
                    <i class="fas fa-user-clock"></i> StudentCourse Management
                </a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Configuration -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsecauhinh"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Setting</span>
        </a>
        <div id="collapsecauhinh" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category:</h6>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/SemestersManage/Index">
                    <i class="fas fa-calendar-alt"></i> Semesters
                </a>
                <a class="collapse-item" asp-area="" asp-page="/AdminMenu/StudentClassesManage/Index">
                    <i class="fas fa-users-cog"></i> Student Classes <br /> Management
                </a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

<!-- End of Sidebar -->

ScoreManage-main/ScoreManagement/Pages/Shared/_SidebarLecturer.cshtml
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/LectureMenu/LecturerDashboard">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Score Management</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="/LectureMenu/LecturerDashboard">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Lecturer Dashboard</span>
        </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Nav Item - Academic Management -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
           aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-book"></i>
            <span>Learning Management</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Category:</h6>
                <a class="collapse-item" asp-area="" asp-page="/LectureMenu/LecturerDashboard">
                    <i class="fas fa-book-reader"></i> Lecturer`s classes
                </a>
 @*                <a class="collapse-item" asp-area="" asp-page="/LectureMenu/CoursesManage/Index">
                    <i class="fas fa-book"></i> Môn học
                </a>
                <a class="collapse-item" asp-area="" asp-page="/LectureMenu/ClassesManage/Index">
                    <i class="fas fa-school"></i> Lớp học
                </a>
                <a class="collapse-item" asp-area="" asp-page="/LectureMenu/MajorManage/Index">
                    <i class="fas fa-graduation-cap"></i> Ngành học
                </a> *@
            </div>
        </div>
    </li>


    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

ScoreManage-main/ScoreManagement/Pages/Shared/_Topbar.cshtml
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    @* <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                   aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
 *@
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Alerts Dropdown -->
        @* <li class="nav-item dropdown no-arrow mx-1"> *@
        @*     <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" *@
        @*        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> *@
        @*         <i class="fas fa-bell fa-fw"></i> *@
        @*         <span class="badge badge-danger badge-counter">3+</span> *@
        @*     </a> *@
        @*     <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" *@
        @*          aria-labelledby="alertsDropdown"> *@
        @*         <h6 class="dropdown-header">Alerts Center</h6> *@
        @*         <!-- Alert Items --> *@
        @*         <a class="dropdown-item d-flex align-items-center" href="#"> *@
        @*             <div class="mr-3"> *@
        @*                 <div class="icon-circle bg-primary"> *@
        @*                     <i class="fas fa-file-alt text-white"></i> *@
        @*                 </div> *@
        @*             </div> *@
        @*             <div> *@
        @*                 <div class="small text-gray-500">December 12, 2019</div> *@
        @*                 A new monthly report is ready to download! *@
        @*             </div> *@
        @*         </a> *@
        @*         <!-- Add other alerts here --> *@
        @*         <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a> *@
        @*     </div> *@
        @* </li> *@

        @* <!-- Messages Dropdown --> *@
        @* <li class="nav-item dropdown no-arrow mx-1"> *@
        @*     <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" *@
        @*        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> *@
        @*         <i class="fas fa-envelope fa-fw"></i> *@
        @*         <span class="badge badge-danger badge-counter">7</span> *@
        @*     </a> *@
        @*     <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" *@
        @*          aria-labelledby="messagesDropdown"> *@
        @*         <h6 class="dropdown-header">Message Center</h6> *@
        @*         <!-- Message Items --> *@
        @*         <a class="dropdown-item d-flex align-items-center" href="#"> *@
        @*             <div class="dropdown-list-image mr-3"> *@
        @*                 <img class="rounded-circle" src="~/Asset/img/undraw_profile_1.svg" alt="..."> *@
        @*                 <div class="status-indicator bg-success"></div> *@
        @*             </div> *@
        @*             <div class="font-weight-bold"> *@
        @*                 <div class="text-truncate">Hi there! I am wondering if you can help me...</div> *@
        @*                 <div class="small text-gray-500">Emily Fowler · 58m</div> *@
        @*             </div> *@
        @*         </a> *@
        @*         <!-- Add other messages here --> *@
        @*         <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a> *@
        @*     </div> *@
        @* </li> *@

        <!-- User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                <img class="img-profile rounded-circle" src="~/Asset/img/undraw_profile.svg">
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="/AccountLogin/ViewMyProfile">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <form method="post" asp-page="/AccountLogin/Login" asp-page-handler="Logout">
                    <button class="dropdown-item" type="submit">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout
                    </button>
                </form>

            </div>
        </li>
    </ul>
</nav>
<!-- End of Topbar -->